/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1qyqk248Cv0
 */
import {Input} from "@/Components/ui/input"
import React, {useEffect} from "react"
import {ReviewWithItem} from "@/Tools/Interfaces/reviewInterfaces";
import {getLIDescription, getLIName} from "@/Analysis/analysis";
import {Album} from "@/API/Interfaces/albumInterfaces";
import {Track} from "@/API/Interfaces/trackInterfaces";
import {Artist} from "@/API/Interfaces/artistInterfaces";
import {retrieveNumberOfReviews, retrievePaginatedReviews, submitReview} from "@/Tools/reviews";
import {User} from "@/Tools/Interfaces/userInterfaces";
import {createPictureSources, isTrack} from "@/Tools/utils";
import {Skeleton} from "@/Components/ui/skeleton";
import {MultistageDialog} from "@/Components/MultistageDialog";
import {DialogProps} from "@/Components/GenericDialog";
import {Button} from "@/Components/ui/button";
import {Separator} from "@/Components/ui/separator";
import {Textarea} from "@/Components/ui/textarea";
import {Label} from "@/Components/ui/label";
import {debouncedSearchResults} from "@/Tools/search";

import {NotepadText} from "lucide-react";
import {
    Carousel,
    CarouselApi,
    CarouselContent,
    CarouselItem,
    CarouselNext,
    CarouselPrevious
} from "@/Components/ui/carousel";


function SkeletonReviewItem() {
    return (
        <div className="flex flex-col gap-4">
            <Skeleton className={'w-[300px] h-[300px] flex-shrink-0'}/>
            <div className="flex flex-col gap-1">
                <Skeleton className="h-6 w-16"/>
                <Skeleton className="h-4 w-32"/>
                <Skeleton className="h-4 w-20"/>
            </div>
        </div>
    )
}

function ReviewItem(props: { review: ReviewWithItem<Artist | Track | Album> }) {
    let images = null;
    if (isTrack(props.review.item)) {
        images = props.review.item.album.images
    } else {
        images = props.review.item.images
    }
    const imgSrcSet = createPictureSources(images, 0.25)
    return (
        <div className="flex flex-col gap-4 w-fit">
            <div className="flex-shrink-0">
                <img
                    width={300}
                    height={300}
                    alt="Album Cover"
                    className={"aspect-square object-cover"}
                    srcSet={imgSrcSet}
                />
            </div>
            <div className={"relative w-100"}>
                <h2 className="font-semibold text-lg line-clamp-2">{getLIName(props.review.item)}</h2>
                <p className="text-sm text-muted-foreground line-clamp-2">{getLIDescription(props.review.item)}</p>
                <div className="flex items-end gap-1 my-1">
                    {
                        Array(Math.floor(props.review.rating)).fill(0).map((_, i) => {
                            return <StarIcon key={i} className="w-4 h-4 fill-primary"/>
                        })
                    }
                    {
                        Array(Math.ceil(5 - props.review.rating)).fill(0).map((_, i) => {
                            return <StarIcon key={i} className="w-4 h-4"/>
                        })
                    }
                    <span className="text-xs text-muted-foreground">({props.review.rating})</span>
                    {
                        props.review.description &&
                        <NotepadText className="absolute top-1.5 right-0 w-4 h-4 text-muted-foreground"/>

                    }
                </div>
            </div>
        </div>
    )
}

function NewReviewDialog() {

    const [selectedType, setSelectedType] = React.useState<'album' | 'artist' | 'track'>('album')
    const [searchInput, setSearchInput] = React.useState('')
    const [selectedItem, setSelectedItem] = React.useState<Artist | Track | Album | null>(null)
    const [selectedRating, setSelectedRating] = React.useState(5)
    const descriptionRef = React.useRef<HTMLTextAreaElement>(null)

    useEffect(() => {
        if (searchInput) {
            debouncedSearchResults(searchInput, selectedType).then(res => setSelectedItem(res[0]));
        }
    }, [searchInput]);

    const dialogProps: DialogProps[] = [
        {
            trigger: <Button variant={'secondary'}>New</Button>,
            title: "Select an item",
            description: "Select something to review.",
        },
        {
            trigger: <Button variant={'secondary'}>New</Button>,
            title: "Write a description",
            description: "Write a description for your item.",
            action: () => submitReview(selectedItem, selectedRating, descriptionRef.current?.value),
            actionDescription: "Submit",
        }
    ]
    return (
        <MultistageDialog dialogProps={dialogProps}>
            <div className={"flex flex-col gap-4"}>
                <div>
                    <h3>Item type</h3>
                    <p className={"text-muted-foreground"}>Select the type of item you would like to
                        review.</p>
                </div>
                <Separator/>
                <div className={'inline-flex w-full gap-4'}>
                    <Button
                        variant={selectedType === 'album' ? 'default' : 'outline'}
                        onClick={() => setSelectedType('album')}>Album</Button>
                    <Button
                        variant={selectedType === 'artist' ? 'default' : 'outline'}
                        onClick={() => setSelectedType('artist')}>Artist</Button>
                    <Button
                        variant={selectedType === 'track' ? 'default' : 'outline'}
                        onClick={() => setSelectedType('track')}>Track</Button>
                </div>
                <div>
                    <h3><span className={"capitalize"}>{selectedType}</span> name</h3>
                    <p className={"text-muted-foreground"}>Type in the name of the item you would like to review.</p>
                </div>
                <Separator/>
                <div className={'inline-flex w-full gap-4'}>
                    <Input placeholder={`Name of ${selectedType}`} onChange={(e) => setSearchInput(e.target.value)}/>
                </div>
            </div>


            {selectedItem &&
                <div className={"space-y-2"}>
                    <div className="border p-4 rounded">
                        <Label className="sr-only" htmlFor="song">
                            {getLIName(selectedItem)}
                        </Label>
                        <h3>{getLIName(selectedItem)}</h3>
                        <p className={"text-sm text-muted-foreground"}>{getLIDescription(selectedItem)}</p>
                    </div>
                    <div className={"inline-flex gap-2 ml-2 items-end"}>
                        {Array(5).fill(0).map((_, i) => {
                            return (
                                <Button className={"p-0 bg-none"} variant={'ghost'} asChild onClick={() => {
                                    if (selectedRating === i + 1) {
                                        setSelectedRating(i + 0.5)
                                    } else {
                                        setSelectedRating(i + 1)
                                    }
                                }}>
                                    <StarIcon className={`w-6 h-6 ${selectedRating >= i + 1 ? 'fill-primary' : ''}`}/>
                                </Button>
                            )
                        })}
                        <p className={'text-sm text-muted-foreground'}>({selectedRating})</p>
                    </div>
                    <div>
                        <Label className="sr-only" htmlFor="review">
                            Review Content
                        </Label>
                        <Textarea className="min-h-[10rem]" id="review" ref={descriptionRef}
                                  placeholder="Write your review here."/>
                    </div>
                </div>
            }


        </MultistageDialog>
    )
}

export function UserReviews(props: { user: User | null }) {
    const {user} = props
    const [numOfReviews, setNumOfReviews] = React.useState(1)
    const numOfPages = Math.ceil(numOfReviews / 3)
    const [reviews, setReviews] = React.useState<ReviewWithItem<Artist | Track | Album>[]>([])
    const [carouselApi, setCarouselApi] = React.useState<CarouselApi>(null)

    React.useEffect(() => {
        if (user) {
            retrieveNumberOfReviews(user.id).then(res => {
                    setNumOfReviews(res)
                }
            )
            retrievePaginatedReviews(user.id, 1, 6).then(res => {
                setReviews(res.items)
            })
        }
    }, [user])



    return (
        <div className="flex flex-col items-center px-4 py-6 mx-auto space-y-6">
            <Input placeholder="Search..." type="search"/>
            <Carousel className="w-full max-w-xs lg:max-w-full">
                <CarouselContent>
                    {
                        reviews.length > 0 ?
                            reviews.map((review, index) => {
                                return (
                                    <CarouselItem className={"lg:basis-1/3"} key={index}>
                                        <ReviewItem review={review}/>
                                    </CarouselItem>
                                )
                            })
                            :
                            Array(3).fill(0).map((_, i) => {
                                return (
                                    <CarouselItem className={"lg:basis-1/3"} key={i}>
                                        <SkeletonReviewItem/>
                                    </CarouselItem>
                                )
                            })
                    }
                </CarouselContent>
                <CarouselPrevious className={"hidden sm:block"}/>
                <CarouselNext className={"hidden sm:block"}/>
            </Carousel>
            <NewReviewDialog/>
        </div>
    )
}


function SearchIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="11" cy="11" r="8"/>
            <path d="m21 21-4.3-4.3"/>
        </svg>
    )
}


function StarIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon
                points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
        </svg>
    )
}
