name: Janitor Nightly Job

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_janitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run janitor.js
        run: node actions/janitor.js ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.POCKETBASE_EMAIL }} ${{ secrets.POCKETBASE_PASSWORD }}
